http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  service1:
    host: localhost
    paths: ['/service1', '/service1/*']
  service2:
    host: localhost
    paths: ['/service2', '/service2/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  service1Service:
    url: 'http://localhost:3000'
  service2Service:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  service1Pipeline:
    apiEndpoints:
      - service1
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: service1Service
              changeOrigin: true
  service2Pipeline:
    apiEndpoints:
      - service2
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: service2Service
              changeOrigin: true
